Fixed responsiveness of sponsor
SolarChapter/old-solarchapter-website pull request #18
Opened 2018-09-17 04:59 UTC by DaveIstanto

Edits were made in index.html and assets/sass/main.css.

Note:
on line 240, ul style is still hard-coded. Would be better if it is in the main.css. Can @linahsie do this real quick, still not used to the nested and inherited classes?

Thank you

2018-09-18 05:14 UTC, linahsie commented on assets/sass/main.css
> +@charset "UTF-8";
@DaveIstanto kok file ini changes nya bisa banyak banget?

2018-09-18 05:14 UTC, linahsie commented on assets/sass/main.scss
> +.sponsor-list a {
Ini bisa di nested di dalem .sponsor-list { 

```
.sponsor-list {   
     padding: 1em;   
    ...
     a {
          border-bottom: none;
     }
}

2018-09-18 05:14 UTC, linahsie commented on assets/sass/main.scss
> +  justify-content: center; }
} in a new line

2018-09-18 05:14 UTC, linahsie commented on assets/sass/main.scss
> +  max-width: 60%; }
} in newline

2018-09-18 05:16 UTC, DaveIstanto commented on assets/sass/main.css
> +@charset "UTF-8";
@linahsie iya, I changed almost all the sponsor styling in the scss file

2018-09-18 05:31 UTC, linahsie commented on assets/sass/main.scss
> +  margin-top: 5%;
5% margin ini buat apa?

2018-09-18 05:33 UTC, linahsie commented on assets/sass/main.scss
> +  .sponsor-list a {
kalo nested gini, gausa tulis
``` .sponsor-list a {```
langsung tulis nya 
```a { ```

for more reference: https://sass-lang.com/guide

2018-09-19 03:50 UTC, DaveIstanto commented on assets/sass/main.scss
> +  margin-top: 5%;
Buat space between sponsor boxes, so they're not too close together, but in % jadi responsive

2018-09-19 04:44 UTC, DaveIstanto commented on assets/sass/main.css
> -  .container.\37 5\25			{
@linahsie ini buat apa ya lin \37 5\25, diganti percentage soalnya

2018-09-19 04:56 UTC, DaveIstanto commented on assets/sass/main.css
> +.\4 u, .\4u\$ {
@linahsie These parts somehow changes \34 to 4 , and 24 to $.

2018-09-27 21:18 UTC, linahsie requested changes
few updates before merging!

2018-09-27 21:18 UTC, linahsie commented on assets/sass/main.css
> +  a {
since gak pake scss, a nya bisa dikeluarin (as in like jadi after } nya sponsor-list, add `.sponsor-list a {...`

2018-09-27 21:18 UTC, linahsie commented on assets/sass/main.css
> +  flex-wrap: wrap; }
add newline after this

2018-09-27 21:30 UTC, linahsie reviewed
styling nit

2018-09-27 21:30 UTC, linahsie commented on assets/sass/main.css
> +  margin-left: 1%;
margin2 ini kenapa pake %? kalo misalnya pake px gimana? gua coba2 ganti semua margin top right left jadi 5px looks fine sih.

2018-09-28 05:00 UTC, DaveIstanto commented on assets/sass/main.css
> +  margin-left: 1%;
% bikin marginnya responsive lin, https://stackoverflow.com/questions/12450961/responsive-layout-px-em-or

2018-09-29 02:40 UTC, linahsie requested changes
remove newlines

2018-09-29 02:40 UTC, linahsie commented on assets/sass/main.css
> +
nit: remove newline

2018-09-29 02:40 UTC, linahsie commented on assets/sass/main.css
> +
remove extra empty newline

2018-09-29 02:40 UTC, linahsie commented on assets/sass/main.css
> +
nit: remove extra empty newline

2018-09-29 02:40 UTC, linahsie commented on assets/sass/main.css
> +
nit: remove extra empty newline

2018-09-29 02:40 UTC, linahsie commented on assets/sass/main.css
> +
nit: remove extra empty newline

2018-09-30 22:05 UTC, linahsie approved these changes

2018-10-01 07:50 UTC, merged

2018-10-01 07:52 UTC, linahsie commented
Duplicate issue #12