Add video gege
SolarChapter/old-solarchapter-website pull request #34
Opened 2018-10-29 08:13 UTC by DaveIstanto

Addressing issue #33

2018-10-29 18:14 UTC, linahsie requested changes

2018-10-29 18:14 UTC, linahsie commented on index.html
> +            <section class="wrapper style3 container special" id="our-message">
Ini masukin di section <--Three--> aja gausa bikin section baru

2018-10-29 18:14 UTC, linahsie commented on assets/sass/main.css
> +}
add newline between styling
```{r}
}
  <-- newline
.iframe-container iframe {
```

2018-10-29 18:14 UTC, linahsie commented on assets/sass/main.css
> +.iframe-container iframe{
space between class name and {

2018-10-30 01:03 UTC, DaveIstanto commented on index.html
> +            <section class="wrapper style3 container special" id="our-message">
updated in the newest commit

2018-10-30 01:14 UTC, DaveIstanto commented
@linahsie since fix_chap_1_responsiveness is done, duplicate lines for the same iframe container style is removed here.

2018-10-30 03:49 UTC, linahsie approved these changes

2018-10-30 03:50 UTC, merged